
import "./globals.scss";
import "@/assets/style/styles.scss";
import Footer from "@/CommonComponents/Footer/Footer";
import Header from "@/CommonComponents/Header/Header";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  );
}
